### ISSUE TITLE
Put all constants in the Constants class

### ISSUE THREAD

**Issue by josephhadad05** [Creekside-Robotics/Creekside-8775-Robotics-2022-Offseason#18]
Go through the code and save hardcoded numbers as constants in the proper location.

- [ ] Subsystems specific constants should be saved in their subsystems as a variable with the keywords "private" and "final"
- [ ] Global variables should be saved in the Constants.java file with the keywords "public" and "static"

**Comment by paulelliott** [comment]
I would encourage you to think about what we call scoping when you move constants around. A `Constants.java` class fine for globals. Things that might used and applied in many contexts all over the codebase. If a constant is specific to a certain subsystem etc then I would recommend leaving it in the class where it will be used.

**Comment by josephhadad05** [comment]
I think that might be better, thanks for the tip.
