### ISSUE TITLE
Create camera subsystem

### ISSUE THREAD

**Issue by josephhadad05** [Creekside-Robotics/Creekside-8775-Robotics-2022-Offseason#6]
Abstract class representing a camera.
Parameters:
- Camera name and pipeline index 
- Camera Height and offset from robot center.
- Target height

Must include methods that:
- Return if there are any objects detected
- Get object translation relative to center of robot 

Abstract methods that:
- Return trajectory to move to object

**Comment by paulelliott** [comment]
The implementation of this looks like a great opportunity to write some automated tests to ensure the behavior works as expected. If whoever picks this up would like to, I would be happy to pair program on this to show you how to do TDD (test-driven development).
