### ISSUE TITLE
Create Pickup Command

### ISSUE THREAD

**Issue by josephhadad05** [Creekside-Robotics/Creekside-8775-Robotics-2022-Offseason#7]
## Auto-Pickup Command
The Auto-Pickup command should run the intake while moving towards and over the nearest ball to pick it up. Should be a standard command that runs a Parallel command group within initialize method (right click on the commands folder within vscode and click the "create new class/command" option) 

#### Constructor
Within the constructor, the drivetrain, intake, and BallCamera objects should all be passed as parameters and stored in as object variables. 

#### Initialize method
Within the initialize method store the return value of a call to the `getTrajectory` method in another object variable. If that trajectory is non-`null` (meaning the goal was detected), store and schedule a command that does the following as object variable:

- Run `FollowTrajectory` Command with Trajectory returned by the `getTrajectory` method in the GoalCamera subsystem (currently stored in an instance variable), this will move the robot over the ball. While this is happening run the intake to pick up the ball.

#### End method
Within the overridden end method cancel the command in the instance field, meaning that the command is finished.

#### Is Finished method
If the trajectory is `null` the function should return true (meaning, there is no goal detected and the command ends before it even begins). After that statement return whether or not the command stored has finished. 
_The reason for this ordering is to first verify that the command is not null to avoid a null pointer exception._

#### Helpful Docs
- [Commands](https://docs.wpilib.org/en/stable/docs/software/commandbased/commands.html)
- [Command Groups](https://docs.wpilib.org/en/stable/docs/software/commandbased/command-groups.html)
- [Command Scheduler](https://docs.wpilib.org/en/stable/docs/software/commandbased/command-scheduler.html)

**Comment by paulelliott** [comment]
The implementation of this looks like a great opportunity to write some automated tests to ensure the behavior works as expected. If whoever picks this up would like to, I would be happy to pair program on this to show you how to do TDD (test-driven development).

**Comment by josephhadad05** [comment]
Depends on #8
